---
volumes:
  tms-portal-postgres-data:

networks:
  rabbitmq_netwrk:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: tms_portal_postgres
    labels:
      name: tms_portal_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PG_ADMIN_PASS
    ports:
      - $PG_PORT:5432
    volumes:
      - tms-portal-postgres-data:/var/lib/postgresql/data

  adminer:
      image: adminer
      restart: always
      ports:
        - 9090:8080
      volumes:
        - tms-portal-postgres-data:/var/lib/postgresql/data