#!/bin/bash

# Cleanup of init-db
# TODO:  Cleanup init script stuff if it becomes necessary

kubectl delete -f deploy.yml

# if you want to delete postgres disk, run this:  kubectl delete -f pvc-postgres.yml
